name: openmc-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.21
  - scipy
  - cython
  - matplotlib
  - notebook
  - nb_conda_kernels
  - pandas
  - uncertainties
  - lxml
  - pytest
  - requests
  - entrypoints
  - pyyaml
  - vtk
  - coverage
  - pytest-cov
  - colorama
