name: pyne-env
channels:
  - conda-forge
  - file:///home/ooblack/miniconda3/envs/cpython-env/conda-bld/
dependencies:
  - python=3.9.10=debug
  - numpy
  - scipy
  - cython
  - matplotlib
  - notebook
  - nb_conda_kernels
    # - openmc=0.13.0=nodagmc*
  - pytables
  - pip:
    - Jinja2
    - progress
    - nose
    - future
  
