name: pyne-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - scipy
  - cython
  - matplotlib
  - notebook
  - nb_conda_kernels
    # - openmc=0.13.0=nodagmc*
  - pytables
  - pip:
    - Jinja2
    - progress
    - nose
    - future
