name: openmc-dagmc-env
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - cython
  - matplotlib
  - notebook
  - nb_conda_kernels
  - pandas
  - uncertainties
  - lxml
  - pytest
  - requests
  - entrypoints
  - pyyaml
  - vtk
  - coverage
  - pytest-cov
  - colorama
